### ISSUE TITLE
Fix for some glyphs

### ISSUE THREAD

**Issue by enathu** [VanillaandCream/Catamaran-Tamil#1]
First of all, thank you for designing and developing this awesome Tamil unicode font. 

Couple of glyphs in the font, isn't representing correct letterform of Tamil script. Namely னு, ணு, ழு and ழூ. I've made a quick infographic to illustrate the corrections. Please have a look.

![cata-03](https://cloud.githubusercontent.com/assets/62147/7758421/720563b0-0001-11e5-93ed-953b60294cb9.png)

Also, you can use my fork of Tamil font testing page to test the fonts: http://niram.org/tamil-font-test/

Thank you.

**Comment by VanillaandCream** [comment]
Hi Tharique.,

Thanks for the suggestions, I will look into them asap.

Best,
Pria

**Comment by enathu** [comment]
Hi Pria, 

Sorry for tad delay in replying. I totally understand your design decision behind the style of the letter form of your Catamaran's ழு and ழூ. But, the problem with those glyphs is that it is not really denoting the very letters, itself. I've personally seen in some magazines, they have used a font with this kind of glyph for a heading and replaced this very glyph with some other similar / not-so similar font. That's totally awkward.

If you look at the web font usage, most of the / pretty much every site that uses web font uses the Droid Sans Tamil / Noto Sans Tamil and others uses the Latha - the default Windows font. And in iOS, there is a font named TamilSangam - all these fonts are using the standard style ழு letter form. 

So to say, I've quickly culled some screenshots from today's various newspapers from India and Sri Lanka. As you can see they all were using the standard style of ழு letter form in all the fonts, which is what native readers are familiar with. Please have a look.

![lluu](https://cloud.githubusercontent.com/assets/62147/7796562/6973485a-02d8-11e5-8c91-ebb551e9f061.jpg)
![l4](https://cloud.githubusercontent.com/assets/62147/7796558/5e8a0668-02d8-11e5-8e18-4b75e09e0427.jpg)
![l2](https://cloud.githubusercontent.com/assets/62147/7796565/6f9e8d2a-02d8-11e5-9306-5becc69d2e8f.jpg)
![l3](https://cloud.githubusercontent.com/assets/62147/7796567/726e35aa-02d8-11e5-80b2-b8035e2c8aec.jpg)
![l5](https://cloud.githubusercontent.com/assets/62147/7796569/760e99c0-02d8-11e5-8028-6220531896ae.jpg)
![l6](https://cloud.githubusercontent.com/assets/62147/7796571/78d9a910-02d8-11e5-8091-9edd5ebad37c.jpg)

As you've pointed out as in the ITF alternate styling, but I truly don't know, where this ழு alternate style was initiated. I have a "Curious case of ழு" title in my mind to research and write about it. I've also, contacted Johny last year with some suggestions for Karla as it uses the obsolete styling as the default for ligatures like லை, ளை, etc. , and he said, he'll look on to them when he gets to work on the update.

I really love to see this Catamaran across the web and this small style change for ழு will make a big difference in the readers/editors mind, to choose this for their sites. I am suggesting to please consider this standard styling for ழு as it's the familiar letter form version for native readers. I'd love to hear your thoughts on this, Pria.

Thanks.

Best smile,
Tharique Azeez

**Comment by VanillaandCream** [comment]
Hi Tharique.,

I am extremely motivated by your passion on this subject. I am a native
Tamilian as well and the current state of Tamil typography was what led me
to pursue type-design as a serious career option.

Thanks so much for pointing out the usage in text settings. Over the last
year I took some time to check out the preferences for Tamil typography at
Sri Lanka, Singapore and Chennai. Somehow this was not an area I looked
well into. We should have spoken earlier!

The interesting thing about a platform such as Google fonts is to change
some of the issues of Tamil typography, as reading preferences are not yet
well established in the web medium. As you might be aware, historically a
lot of decisions on this subject were made by the missionaries so that they
can quickly convert the Bible and spread the word. In that the works of the
American Mission Press are notable as they set the standards for using
inclined type in text settings. The opening of this new media gives us all
a chance to experiment. That is one of the reasons for designing an upright
Tamil versus the slanted style, to see how the reception is, and can this
medium change established preferences. This is kind of necessary if
rich typographic settings in the foreseeable future have to become a
defacto standard for Tamil.

I don't mean to hurt your feelings, but I really want to see typography
that bridges the gap between writing and lettering. While most other
instances of Catamaran are conservative, this is possibly the only area
where it doesn't adhere to the norms. And in that, having a leg in these
two worlds, I do feel like if I do not do these things and present an
advocacy for them, who will?

While I am not absolutely averse to the idea of adding your suggestions as
stylistic alternates, it is surely not making it as the default settings.
That is a risk I am willing to take and see what yields of this
experimentation.

Dave, please will you comment if I should add it as a stylistic alternate.

Are you located in Chennai? If so, we should meet soon.

Best,
Pria

**Comment by enathu** [comment]
Hi Pria,

Thank you for your reply. I do share the same reason and passion with you, as I looked at the current state of Tamil typography, I was really in passionate about it and wanted to do something about it. Since last year, I've started to log, Tamil hand lettering and typography awesomeness. You can have a look at it, in case you missed it. There are hundreds of hand lettering pieces available in my [**site**](http://tamiltypography.niram.org/)

I do clearly and passionately love the evolution in lettering and typography. And I am all in for experimentation too, as I have released Unicode compliant Tamil font with the flavour of handwriting: [**Neythal**](https://github.com/enathu/neythal-font), last year.  This handwriting Unicode font is an experimentation, and first of its kind, AFAIK in terms of Tamil typography.

As you already aware, that looking at early Tamil epigraphy, we understand many things have changed. From *Veeramaa Munivar* to *Periyaar*, there were many reforms in the script. This simple inscription from 11th century speaks itself. 

![An inscription from 11th century](https://cloud.githubusercontent.com/assets/62147/7798951/2bd5c7d2-02f8-11e5-953b-4543f029bfdc.jpg)

Yeah, having stylistic alternate to such glyphs come in handy for those who want to have it in there text settings or typography arrangements, I reckon.

Pria, I am based in UK & Sri Lanka. But, hey we are living in the virtual world. We should catch up real soon, to dig this stuff, deeper. I've some more ideas and thoughts on Tamil lettering and typography. Let's talk.

Thanks.

Best smile,
Tharique Azeez

**Comment by VanillaandCream** [comment]
Hi Tharique., I am moving this conversation to our personal email accounts.

Best,
Pria
