### ISSUE TITLE
Add to README an explanation of the repository layout

### ISSUE THREAD

**Issue by davelab6** [VanillaandCream/Catamaran-Tamil#6]
I'm confused a bit by the repository layout. There are 4 glyphs source files in https://github.com/VanillaandCream/Catamaran-Tamil/tree/master/Instances - how to get from those to the TTFs?

**Comment by VanillaandCream** [comment]
Make TTs from each of it in sequence, since it has five masters, each file
generates 3 instances, and sometimes the same weight is generated twice, I
have to choose which one to keep, though it doesn't change anything by
keeping any of the versions.

What do you hate about the Kk? I like it, any suggestions on how to improve
it?

Best
Pria

**Comment by davelab6** [comment]
> Make TTs from each of it in sequence

I made PR #8 to put this information into the repo

> What do you hate about the Kk? I like it, any suggestions on how to improve it?

I'll file a separate issue for this
